--PL/SQL-Objekte
DROP TRIGGER trigger_buchung_stonieren;
DROP FUNCTION preis;
DROP SEQUENCE seq_StornierteBuchungen;

-- Views
DROP VIEW Buchung;
DROP VIEW Reservierung;
DROP VIEW Familienwohnungen;
DROP VIEW UebersichtKunden;
DROP VIEW Zahlungsstatus;
DROP VIEW MidAgeKunden;
DROP VIEW MidAgeKundenOhneGebDatum;
DROP VIEW GuteFluggesellschaften;

-- Tabellen
DROP TABLE Rechnung CASCADE CONSTRAINTS;
DROP TABLE Ferienwohnung_hat_Zusatzausstattung CASCADE CONSTRAINTS;
DROP TABLE Bild CASCADE CONSTRAINTS;
DROP TABLE verbindet CASCADE CONSTRAINTS;
DROP TABLE Entfernung CASCADE CONSTRAINTS;
DROP TABLE Touristenattraktion CASCADE CONSTRAINTS;
DROP TABLE Belegung CASCADE CONSTRAINTS;
DROP TABLE Kunde CASCADE CONSTRAINTS;
DROP TABLE Ferienwohnung CASCADE CONSTRAINTS;
DROP TABLE Flughafen CASCADE CONSTRAINTS;
DROP TABLE Fluggesellschaft CASCADE CONSTRAINTS;
DROP TABLE Adresse CASCADE CONSTRAINTS;
DROP TABLE Ort CASCADE CONSTRAINTS;
DROP TABLE Bankverbindung CASCADE CONSTRAINTS;
DROP TABLE Zusatzausstattung CASCADE CONSTRAINTS;
DROP TABLE Land CASCADE CONSTRAINTS;
DROP TABLE AdditionalDocumentation CASCADE CONSTRAINTS;
DROP TABLE StornierteBuchung CASCADE CONSTRAINTS;